Upgraded to 16.04

diff --git a/ubuntu/nodejs/8.11.0/Dockerfile b/ubuntu/nodejs/8.11.0/Dockerfile
--- a/ubuntu/nodejs/8.11.0/Dockerfile
+++ b/ubuntu/nodejs/8.11.0/Dockerfile
@@ -10,7 +10,7 @@
 # See the License for the specific language governing permissions and limitations under the License.
 #
 
-FROM ubuntu:14.04.5
+FROM ubuntu:16.04
 
 ENV DOCKER_BUCKET="download.docker.com" \
     DOCKER_VERSION="17.09.0-ce" \
@@ -20,51 +20,41 @@ ENV DOCKER_BUCKET="download.docker.com" \
     DOCKER_COMPOSE_VERSION="1.21.2" \
     GITVERSION_VERSION="3.6.5"
 
-# Install git, SSH, and other utilities
-RUN set -ex \
-    && echo 'Acquire::CompressionTypes::Order:: "gz";' > /etc/apt/apt.conf.d/99use-gzip-compression \
+RUN echo "deb mirror://mirrors.ubuntu.com/mirrors.txt xenial main restricted universe multiverse" > /etc/apt/sources.list && \
+    echo "deb mirror://mirrors.ubuntu.com/mirrors.txt xenial-updates main restricted universe multiverse" >> /etc/apt/sources.list && \
+    echo "deb mirror://mirrors.ubuntu.com/mirrors.txt xenial-security main restricted universe multiverse" >> /etc/apt/sources.list && \
+    DEBIAN_FRONTEND=noninteractive apt-get update
+
+RUN readonly __packages=" \
+    ca-certificates \
+    curl \
+    git \
+    build-essential \
+    less \
+    mime-support \
+    openssl \
+    perl \
+    python \
+    unzip \
+    wget \
+    zip \
+    openssh-client \
+    software-properties-common \
+    apt-transport-https \
+    " \
     && apt-get update \
-    && apt-get install software-properties-common -y --no-install-recommends \
-    && apt-add-repository ppa:git-core/ppa \
-    && apt-get update \
-    && apt-get install git=1:2.* -y --no-install-recommends \
-    && git version \
-    && apt-get install -y --no-install-recommends openssh-client=1:6.6* \
+    && apt-get upgrade --assume-yes \
+    && apt-get install --no-install-recommends \
+    --assume-yes \
+    ${__packages} \
+    # clean up apt cache to make Docker image slimmer
+    && apt-get clean \
     && mkdir ~/.ssh \
     && touch ~/.ssh/known_hosts \
     && ssh-keyscan -t rsa,dsa -H github.com >> ~/.ssh/known_hosts \
     && ssh-keyscan -t rsa,dsa -H bitbucket.org >> ~/.ssh/known_hosts \
-    && chmod 600 ~/.ssh/known_hosts \
-    && apt-get install -y --no-install-recommends \
-       wget=1.15-* python=2.7.* python2.7-dev=2.7.* fakeroot=1.20-* ca-certificates \
-       tar=1.27.* gzip=1.6-* zip=3.0-* autoconf=2.69-* automake=1:1.14.* \
-       bzip2=1.0.* file=1:5.14-* g++=4:4.8.* gcc=4:4.8.* imagemagick=8:6.7.* \
-       libbz2-dev=1.0.* libc6-dev=2.19-* libcurl4-openssl-dev=7.35.* libdb-dev=1:5.3.* \
-       libevent-dev=2.0.* libffi-dev=3.1~* libgeoip-dev=1.6.* libglib2.0-dev=2.40.* \
-       libjpeg-dev=8c-* libkrb5-dev=1.12+* liblzma-dev=5.1.* \
-       libmagickcore-dev=8:6.7.* libmagickwand-dev=8:6.7.* libmysqlclient-dev=5.5.* \
-       libncurses5-dev=5.9+* libpng12-dev=1.2.* libpq-dev=9.3.* libreadline-dev=6.3-* \
-       libsqlite3-dev=3.8.* libssl-dev=1.0.* libtool=2.4.* libwebp-dev=0.4.* \
-       libxml2-dev=2.9.* libxslt1-dev=1.1.* libyaml-dev=0.1.* make=3.81-* \
-       patch=2.7.* xz-utils=5.1.* zlib1g-dev=1:1.2.* unzip=6.0-* curl=7.35.* \
-       e2fsprogs=1.42.* iptables=1.4.* xfsprogs=3.1.* xz-utils=5.1.* \
-       mono-mcs=3.2.* less=458-* groff=1.22.* liberror-perl=0.17-* \
-       asciidoc=8.6.* build-essential=11.* bzr=2.6.* cvs=2:1.12.* cvsps=2.1-* docbook-xml=4.5-* docbook-xsl=1.78.* dpkg-dev=1.17.* \
-       libdbd-sqlite3-perl=1.40-* libdbi-perl=1.630-* libdpkg-perl=1.17.* libhttp-date-perl=6.02-* \
-       libio-pty-perl=1:1.08-* libserf-1-1=1.3.* libsvn-perl=1.8.* libsvn1=1.8.* libtcl8.6=8.6.* libtimedate-perl=2.3000-* \
-       libunistring0=0.9.* libxml2-utils=2.9.* libyaml-perl=0.84-* python-bzrlib=2.6.* python-configobj=4.7.* \
-       sgml-base=1.26+* sgml-data=2.0.* subversion=1.8.* tcl=8.6.* tcl8.6=8.6.* xml-core=0.13+* xmlto=0.0.* xsltproc=1.1.* \
-    && rm -rf /var/lib/apt/lists/* \
-    && apt-get clean
+    && chmod 600 ~/.ssh/known_hosts
 
-# Download and set up GitVersion
-RUN set -ex \
-    && wget "https://github.com/GitTools/GitVersion/releases/download/v${GITVERSION_VERSION}/GitVersion_${GITVERSION_VERSION}.zip" -O /tmp/GitVersion_${GITVERSION_VERSION}.zip \
-    && mkdir -p /usr/local/GitVersion_${GITVERSION_VERSION} \
-    && unzip /tmp/GitVersion_${GITVERSION_VERSION}.zip -d /usr/local/GitVersion_${GITVERSION_VERSION} \
-    && rm /tmp/GitVersion_${GITVERSION_VERSION}.zip \
-    && echo "mono /usr/local/GitVersion_${GITVERSION_VERSION}/GitVersion.exe \$@" >> /usr/local/bin/gitversion \
-    && chmod +x /usr/local/bin/gitversion
 
 # Install Docker
 RUN set -ex \
@@ -84,12 +74,39 @@ RUN set -ex \
 # Ensure docker-compose works
     && docker-compose version
 
+RUN set -ex \
+    && add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" \
+    && readonly __docker_packages=" \
+    docker-ce=17.12.0* \
+    iptables=1.6.0-* \
+    libltdl7=2.4.6-* \
+    libnfnetlink0=1.0.1-* \
+    libxtables11=1.6.0-* \
+    " \
+    && apt-get update \
+    && apt-get install --no-install-recommends --allow-unauthenticated \
+    --assume-yes \
+    ${__docker_packages} \
+    # clean up apt cache to make Docker image slimmer
+    && apt-get clean \
+    # install Docker compose - from official page https://docs.docker.com/compose/install/#install-compose
+    && readonly __docker_compose_version="1.18.0" \
+    && curl --show-error \
+    --location \
+    https://github.com/docker/compose/releases/download/${__docker_compose_version}/docker-compose-$(uname -s)-$(uname -m) \
+    --output \
+    /usr/local/bin/docker-compose \
+    && chmod +x /usr/local/bin/docker-compose \
+    && docker --version \
+    && docker-compose --version
+
 # Install dependencies by all python images equivalent to buildpack-deps:jessie
 # on the public repos.
 
 RUN set -ex \
     && wget "https://bootstrap.pypa.io/2.6/get-pip.py" -O /tmp/get-pip.py \
     && python /tmp/get-pip.py \
+    && pip install --upgrade pip \
     && pip install awscli==1.* \
     && rm -fr /var/lib/apt/lists/* /tmp/* /var/tmp/*
 
@@ -116,7 +133,6 @@ RUN set -ex \
       114F43EE0176B71C7BC219DD50A3051F888C628D \
       7937DFD2AB06298B2293C3187D33FF9D0246406D \
     ; do \
-      gpg --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys "$key" || \
       gpg --keyserver hkp://ipv4.pool.sks-keyservers.net --recv-keys "$key" || \
       gpg --keyserver hkp://pgp.mit.edu:80 --recv-keys "$key" ; \
     done
